chord_recognition/urls.py
from django.conf.urls import url
from . import views

app_name = 'chord_recognition'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^practise/$', views.PractiseView.as_view(), name='practise'),
]

chords/urls.py
from django.conf.urls import url
from . import views

app_name = 'chord_recognition'
urlpatterns = [
    #  url(r'^$', views.index, name='index'),
    #  url(r'^practise/$', views.PractiseView.as_view(), name='practise'),
]

guitar_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^chords/', include('chords.urls')),
    url(r'^minute_changes/', include('minute_changes.urls')),
    url(r'^chord_recognition/', include('chord_recognition.urls')),
    url(r'^admin/', admin.site.urls),
]

minute_changes/urls.py
from django.conf.urls import url
from . import views

app_name = 'minute_changes'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<minute_changes_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^practise/(?P<chord_pair_id>[0-9]+)/$', views.PractiseView.as_view(), name='practise'),
]

chord_recognition/models.py
from django.db import models

# Create your models here.

chords/models.py
from django.db import models


class Chord(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

minute_changes/models.py
from django.db import models
from chords.models import Chord


class Note(models.Model):
    NOTE_CHOICES = (
        ('A', 'A'),
        ('As', 'A#'),
        ('B', 'B'),
        ('C', 'C'),
        ('Cs', 'C#'),
    )

    note = models.CharField(max_length=2, choices=NOTE_CHOICES, default='A')


class ChordPair(models.Model):
    chord1 = models.ForeignKey(
        Chord, related_name='chord1', on_delete=models.PROTECT)
    chord2 = models.ForeignKey(
        Chord, related_name='chord2', on_delete=models.PROTECT)

    def __str__(self):
        return "{} <-> {}".format(self.chord1, self.chord2)


class MinuteChanges(models.Model):
    duration = models.IntegerField(default=1)
    date = models.DateTimeField('Practice Time')
    chord_pair = models.ForeignKey(ChordPair, on_delete=models.PROTECT)
    changes = models.IntegerField(default=0)

    def __str__(self):
        return "{}: ({}) {} change(s) in {} minute(s)".format(
            str(self.date),
            self.chord_pair,
            self.changes,
            self.duration)


def create_chord_pairs(instance, created, raw, **kwargs):
    # not a new chord
    if not created or raw:
        return

    # get all current chords excluding the new one
    chords = Chord.objects.exclude(name=instance.name)
    if len(chords) < 1:
        # no existing chords, can't make pairs
        return

    for chord in chords:
        # create the new pairs. Order doesn't matter
        ChordPair.objects.create(chord1=instance, chord2=chord)


models.signals.post_save.connect(
    create_chord_pairs, sender=Chord, dispatch_uid='create_chord_pairs')

chord_recognition/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View
from django.urls import reverse
from datetime import datetime

from chords.models import Chord

import random


def index(req):
    context = {
        'chords': Chord.objects.all()
    }
    return render(req, 'chord_recognition/index.html', context)


"""
def detail(req, minute_changes_id):
    change = get_object_or_404(MinuteChanges, pk=minute_changes_id)
    return render(req, 'minute_changes/detail.html', {'change': change})
"""


class PractiseView(View):

    EXERCISE_TYPES = ['ssr', 'cpr', 'cqr']

    def get(self, req):
        exercise_type = req.GET.get('type', None)
        if exercise_type is None:
            pass
            exercise_type = self.EXERCISE_TYPES[0]
        if exercise_type not in self.EXERCISE_TYPES:
            return render(req, 'chord_recognition/index.html', {
                'error_message': "That's not a valid exercise type"
            })

        chord_palette = [Chord.objects.get(pk=pk)
                         for pk in req.GET.getlist('chord')]

        num_chords = int(req.GET.get('num_chords', 4))

        # choose a few random chords for the exercise
        chords = [random.choice(chord_palette) for _ in range(num_chords)]

        return render(req, 'chord_recognition/practise.html', {
            'chord_palette': chord_palette,
            'chords': chords
        })

    def post(self, req):
        # return HttpResponseRedirect(reverse('minute_changes:index'))
        return HttpResponse("Chord Practise POST.")

chords/views.py
from django.shortcuts import render

# Create your views here.

minute_changes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import View
from django.urls import reverse
from datetime import datetime
import sys

from django.db.models import Max
from .models import MinuteChanges, ChordPair

def index(req):
    recent_minute_changes = MinuteChanges.objects.order_by('-date')[:5]
    # sort the chord pairs by the maximum number of changes performed for each
    # pair, so that the worst ones appear at the top
    worst_chord_pairs = ChordPair.objects.annotate(max_changes=Max('minutechanges__changes')).order_by('max_changes')
    context = {
        'recent_minute_changes': recent_minute_changes,
        'chord_pairs': worst_chord_pairs
    }
    return render(req, 'minute_changes/index.html', context)

def detail(req, minute_changes_id):
    change = get_object_or_404(MinuteChanges, pk=minute_changes_id)
    return render(req, 'minute_changes/detail.html', {'change': change})

class PractiseView(View):
    def get(self, req, chord_pair_id):
        chord_pair = get_object_or_404(ChordPair, pk=chord_pair_id)
        return render(req, 'minute_changes/practise.html', {'chord_pair': chord_pair})

    def post(self, req, chord_pair_id):
        try:
            chord_pair = ChordPair.objects.get(pk=chord_pair_id)
        except (ValueError, KeyError, ChordPair.DoesNotExist):
            return render(req, 'minute_changes/practise.html', {'chord_pair': chord_pair, 'error_message': "Not a valid chord pair"})
            #return HttpResponseRedirect(reverse('minute_changes:index', args={'error_message': "Not a valid chord pair"}))
        change = MinuteChanges.objects.create(date=datetime.now(), chord_pair=chord_pair, changes=req.POST['changes'])
        return HttpResponseRedirect(reverse('minute_changes:index'))

chord_recognition/templates/chord_recognition/index.html
<h2>Chord Recognition Exercises</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


chord_recognition/templates/chord_recognition/practise.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h3>Practise {{ type }}</h3>
<div>
  <span>Chord Palette: </span>
  <span>{{ chord_palette|join:", " }}</span>
</div>

<div>
  {% for chord in chords %}
    <div>
      <span>{{ chord }}</span>
      <span>dfsdf</span>
    </div>
  {% endfor %}
</div>

{% endblock content %}

minute_changes/templates/minute_changes/detail.html
{{ change }}

minute_changes/templates/minute_changes/index.html
<h2>Previous Minute Changes</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if recent_minute_changes %}
  <ul>
    {% for change in recent_minute_changes %}
      <li><a href="{% url 'minute_changes:detail' change.id %}">{{ change }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No minute changes performed.</p>
{% endif %}

<h2>Practise Now!</h2>
<p>Your worst chord pairs (lowest number of changes, or not yet practiced!) show up first</p>
<p>Practice these ones first!</p>
{% if chord_pairs %}
  <ul>
    {% for pair in chord_pairs %}
      <li><a href="{% url 'minute_changes:practise' pair.id %}">{{ pair }} ({{ pair.max_changes|default:"0" }} changes)</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>Not enough chords have been defined! Please add at least two</p>
{% endif %}

minute_changes/templates/minute_changes/practise.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<script type="text/javascript" src="{% static "js/easytimer.js" %}"></script>
<script type="text/javascript" src="{% static "js/practise.js" %}"></script>

<h3>Practise {{ chord_pair }}</h3>

<div id="timer">
  <span class="prefix">Start in: </span>
  <div class="values">
    <span class="minutes">00</span><span>:</span>
    <span class="seconds">03</span>
  </div>
</div>
<button id="start-btn">Start</button>

<form action="{% url 'minute_changes:practise' chord_pair.id %}" method="POST">
  {% csrf_token %}
  <input type="number" name="changes" min="0" value="0">
  <input type="submit" id="changes-submit" value="Submit" disabled />
</form>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <script src="{% static "js/jquery-3.1.0.js" %}"></script>
        <title>Guitar Practise</title>
    </head>

    <body>
    {% block content %}{% endblock content %}
    </body>
</html>